# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bot.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'bot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbot.proto\x12\x06yh_bot\"7\n\x06Status\x12\x12\n\nrequest_id\x18\x01 \x01(\x03\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\"\x1b\n\rbot_info_send\x12\n\n\x02id\x18\x02 \x01(\t\"\x8c\x03\n\x08\x62ot_info\x12\x1e\n\x06status\x18\x01 \x01(\x0b\x32\x0e.yh_bot.Status\x12\'\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x19.yh_bot.bot_info.Bot_data\x1a\xb6\x02\n\x08\x42ot_data\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07name_id\x18\x03 \x01(\x03\x12\x12\n\navatar_url\x18\x04 \x01(\t\x12\x11\n\tavatar_id\x18\x05 \x01(\x03\x12\x14\n\x0cintroduction\x18\x06 \x01(\t\x12\x11\n\tcreate_by\x18\x07 \x01(\t\x12\x13\n\x0b\x63reate_time\x18\x08 \x01(\x03\x12\x11\n\theadcount\x18\t \x01(\x03\x12\x0f\n\x07private\x18\n \x01(\x05\x12\x0f\n\x07is_stop\x18\x0b \x01(\x05\x12\x14\n\x0c\x61lways_agree\x18\r \x01(\x05\x12\x11\n\tno_detele\x18\x0e \x01(\x05\x12\x16\n\x0e\x64o_not_disturb\x18\x0f \x01(\x05\x12\x0b\n\x03top\x18\x12 \x01(\x05\x12\x13\n\x0bgroup_limit\x18\x14 \x01(\x05\"0\n\nboard_send\x12\x0f\n\x07\x63hat_id\x18\x03 \x01(\t\x12\x11\n\tchat_type\x18\x04 \x01(\x03\"\xe6\x01\n\x05\x62oard\x12\x1e\n\x06status\x18\x01 \x01(\x0b\x32\x0e.yh_bot.Status\x12\'\n\x05\x62oard\x18\x02 \x01(\x0b\x32\x18.yh_bot.board.Board_data\x1a\x93\x01\n\nBoard_data\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x02 \x01(\t\x12\x11\n\tchat_type\x18\x03 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x05 \x01(\x05\x12\x18\n\x10last_update_time\x18\x06 \x01(\x03\x12\x10\n\x08\x62ot_name\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=21
  _globals['_STATUS']._serialized_end=76
  _globals['_BOT_INFO_SEND']._serialized_start=78
  _globals['_BOT_INFO_SEND']._serialized_end=105
  _globals['_BOT_INFO']._serialized_start=108
  _globals['_BOT_INFO']._serialized_end=504
  _globals['_BOT_INFO_BOT_DATA']._serialized_start=194
  _globals['_BOT_INFO_BOT_DATA']._serialized_end=504
  _globals['_BOARD_SEND']._serialized_start=506
  _globals['_BOARD_SEND']._serialized_end=554
  _globals['_BOARD']._serialized_start=557
  _globals['_BOARD']._serialized_end=787
  _globals['_BOARD_BOARD_DATA']._serialized_start=640
  _globals['_BOARD_BOARD_DATA']._serialized_end=787
# @@protoc_insertion_point(module_scope)
